"""Agregar categoria y foto a productos

Revision ID: 52fc441013e5
Revises: 53e6a3d84e81
Create Date: 2026-06-11 09:19:18.249920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fc441013e5'
down_revision = '53e6a3d84e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
