"""Agregar tabla productos y movimientos_producto

Revision ID: 53e6a3d84e81
Revises: 
Create Date: 2026-06-10 15:56:24.874559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e6a3d84e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('tipo_medida', sa.String(length=20), nullable=True),
        sa.Column('precio', sa.Float(), nullable=False),
        sa.Column('stock_actual', sa.Float(), nullable=True),
        sa.Column('activo', sa.Boolean(), nullable=True),
        sa.Column('creado_en', sa.DateTime(), nullable=True),
        sa.Column('actualizado_en', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_producto',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('producto_id', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('cantidad', sa.Float(), nullable=False),
        sa.Column('precio_unitario_momento', sa.Float(), nullable=True),
        sa.Column('total', sa.Float(), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('notas', sa.String(length=255), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('documento_fecha_emision', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('documento_fecha_vencimiento', sa.Date(), nullable=True))

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('documento_fecha_vencimiento')
        batch_op.drop_column('documento_fecha_emision')
        batch_op.drop_column('tipo_documento')

    op.drop_table('movimientos_producto')
    op.drop_table('productos')
    # ### end Alembic commands ###
