"""Agregar unidades a movimientos_producto

Revision ID: a3af0d638f44
Revises: 52fc441013e5
Create Date: 2026-06-11 11:39:30.432953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3af0d638f44'
down_revision = '52fc441013e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidades', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos_producto', schema=None) as batch_op:
        batch_op.drop_column('unidades')

    # ### end Alembic commands ###
